Below is an example of handling exception using "try" and "except" and "finally" block

Here, the user is required to provide a valid integer values for calculating cylinder dimensions.

`
pwd
`{{execute}}

List the file in the current working directory using ls command.

`
ls -l volume-surface-area1.py
`{{execute}}

View the contents of the scripts file.

`
cat volume-surface-area1.py
`{{execute}}


Try to enter characters for radius and height. User is again prompted to enter valid Integer values.

Run the script below to check how exception is handled.

`
python volume-surface-area1.py
`{{execute}}

